name: Checkout Repository

description: Checkout the repository source code

inputs:
  fetch-depth:
    description: Number of commits to fetch
    required: false
    default: "1"

  lfs:
    description: Whether to download Git LFS files
    required: false
    default: "false"

  submodules:
    description: Whether to checkout submodules
    required: false
    default: "false"

  persist-credentials:
    description: Persist Git credentials
    required: false
    default: "true"

runs:
  using: composite

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: ${{ inputs.lfs }}
        submodules: ${{ inputs.submodules }}
        persist-credentials: ${{ inputs.persist-credentials }}