name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/checkout

      - uses: ./.github/actions/setup-node
        with:
          node-version: "22"

      - name: Build application
        run: npm run build

      - uses: ./.github/actions/upload-artifact
        with:
          name: build
          path: dist/
          if-no-files-found: error
          retention-days: 7