name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: production-deploy
  cancel-in-progress: false
  
jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs: [lint]
    uses: ./.github/workflows/build.yml

  package:
    needs: build
    uses: ./.github/workflows/package.yml

  deploy:
    needs: package
    uses: ./.github/workflows/deploy-ec2.yml
    with:
      application-name: cicd_test_deployment
      deployment-group: cicd_deployment
      s3-bucket: jsfaculty.cicd.test.bucket
      aws-region: ap-southeast-1

    secrets:
      aws-role-arn: ${{secrets.AWS_ROLE_ARN}}