name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs: lint
    uses: ./.github/workflows/build.yml

  package:
    needs: build
    uses: ./.github/workflows/package.yml