name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/reusable/lint.yml

  build:
    needs: lint
    uses: ./.github/workflows/reusable/build.yml

  package:
    needs: build
    uses: ./.github/workflows/reusable/package.yml