
name: Deploy

on: 
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.22
      - run: npm ci
      - run: npm run build
      - run: tar -czf dist.tar.gz appspec.yml scripts/ dist/
      - uses: actions/upload-artifact@v4
        with: 
          name: deployment-bundle
          path: dist.tar.gz

  deploy:
    environment: production
    permissions: 
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/download-artifact@v4
        with:
          name: deployment-bundle
          path: .
      - run: ls -la
      - uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::488923400120:role/jsfaculty_cicd_policy_for_test
      - run: aws s3 cp dist.tar.gz s3://jsfaculty.cicd.test.bucket/production/dist.tar.gz
      - run: |
          aws deploy create-deployment \
            --application-name cicd_test_deployment \
            --deployment-group-name cicd_deployment \
            --s3-location bucket=jsfaculty.cicd.test.bucket,bundleType=tgz,key=production/dist.tar.gz