name: Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/checkout

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: "22"

      - name: Lint source code
        run: npm run lint

      # - name: Check formatting
      #   run: npm run format:check