name: Package

on:
  workflow_call:

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Create deployment package
        run: |
          cd build
          tar -czf ../application.tar.gz .

      - uses: ./.github/actions/upload-artifact
        with:
          name: application
          path: application.tar.gz
          if-no-files-found: error
          retention-days: 30